### ISSUE TITLE
add particle effects to players

### ISSUE THREAD

**Issue by amiruqdah** [amiruqdah/mario-party#2]
Right now, our game is pretty lack luster. It could be a lot better if our characters were tweened when they jumped or had some sort of cloud effect when they jumped. There should be a lot more _feeling_ to the movement than there is now. 

@Cranapple Have any ideas/suggestions on how it should look/feel like?

**Comment by ltecot** [comment]
I'm skeptical about any excessive tweening with movement because I think that may break the mario style. However, we should absolutely make fly guys have a little smoke trail as well as add a little poof when fly guys disappear for respawning, or for all characters when the player disconnects. Also a little dust or impact when jumping / stomping may look nice. I'd just play around and see what works.
I'll start messing around with this as well once spawning is solid.

**Comment by amiruqdah** [comment]
Will jump on this later today or tomorrow for sure. @Cranapple

**Comment by amiruqdah** [comment]
Alright, just added some spawn particle effect to the players in 99944695b51dd92603fd70ad5cfccc2656bbbc5d! Will work on run particles and jump particles soon. :shipit:

**Comment by amiruqdah** [comment]
@Cranapple  So this is done. I'm not that satisfied with the walk puff effect but you can play with it and see if you find a better setting for it. As of now, I'm pretty OK with it staying the way it is. You might also notice that there's a bit of a bug regarding player rotation -- and I haven't exactly figured out how to fix this yet since the tweening seems to be done in a separate thread that doesn't update its values from Unity's main thread.
